-- Generated by Oracle SQL Developer Data Modeler 20.3.0.283.0710
--   at:        2021-01-09 15:34:58 EET
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE activitati_de_dezvoltare (
    cod_activitate         INTEGER NOT NULL,
    denumire_activitate    VARCHAR2(400) NOT NULL,
    capacitate_activitate  NUMBER(2)
);

ALTER TABLE activitati_de_dezvoltare ADD CONSTRAINT activitati_de_dezvoltare_pk PRIMARY KEY ( cod_activitate );

CREATE TABLE burse (
    cod_bursa       INTEGER NOT NULL,
    denumire_bursa  VARCHAR2(300),
    valoare_bursa   INTEGER,
    tip_bursa       VARCHAR2(50) NOT NULL
);

ALTER TABLE burse ADD CONSTRAINT burse_pk PRIMARY KEY ( cod_bursa );

CREATE TABLE cataloage (
    cod_catalog        INTEGER NOT NULL,
    nota               NUMBER(10),
    absenta            DATE,
    denumire_situatie  VARCHAR2(20),
    clase_clase_id     NUMBER NOT NULL,
    clase_cod_profil   INTEGER NOT NULL
);

CREATE UNIQUE INDEX cataloage__idx ON
    cataloage (
        clase_clase_id
    ASC );

CREATE UNIQUE INDEX cataloage__idxv1 ON
    cataloage (
        clase_cod_profil
    ASC );

ALTER TABLE cataloage ADD CONSTRAINT cataloage_pk PRIMARY KEY ( cod_catalog,
                                                                clase_cod_profil );

CREATE TABLE clase (
    an_clasa          NUMBER(4) NOT NULL,
    grupa_clasa       CHAR(1) NOT NULL,
    capacitate_clasa  NUMBER(2),
    cod_profil        INTEGER NOT NULL
);

ALTER TABLE clase ADD CONSTRAINT clase_cod_profil_un UNIQUE ( cod_profil );

CREATE TABLE concursuri (
    nume_concurs                               VARCHAR2(100) NOT NULL,
    materie_testata                            VARCHAR2(50) NOT NULL,
    perioada                                   TIMESTAMP NOT NULL, 
--  ERROR: Column name length exceeds maximum allowed length(30) 
         concursuri_olimpiade_id_concurs_olimpiada  INTEGER NOT NULL, 
--  ERROR: Column name length exceeds maximum allowed length(30) 
         concursuri_olimpiade_elevi_id_elev         INTEGER
    NOT NULL, 
--  ERROR: Column name length exceeds maximum allowed length(30) 
         concursuri_olimpiade_cod_profil            INTEGER NOT NULL
);

ALTER TABLE concursuri
    ADD CONSTRAINT concursuri_pk PRIMARY KEY ( concursuri_olimpiade_id_concurs_olimpiada,
                                               concursuri_olimpiade_elevi_id_elev,
                                               concursuri_olimpiade_cod_profil );

CREATE TABLE concursuri_olimpiade (
    id_concurs_olimpiada  INTEGER NOT NULL,
    tip_premiu_obtinut    VARCHAR2(100),
    punctaj_acumulat      NUMBER(100),
    elevi_id_elev         INTEGER NOT NULL,
    elevi_cod_profil      INTEGER NOT NULL,
    cod_profil            INTEGER NOT NULL
);

ALTER TABLE concursuri_olimpiade
    ADD CONSTRAINT concursuri_olimpiade_pk PRIMARY KEY ( id_concurs_olimpiada,
                                                         elevi_id_elev,
                                                         cod_profil );

CREATE TABLE discipline (
    id_disciplina          INTEGER NOT NULL,
    denumire_disciplina    VARCHAR2(150) NOT NULL,
    cataloage_cod_catalog  INTEGER NOT NULL,
    cod_profil             INTEGER NOT NULL
);

ALTER TABLE discipline
    ADD CONSTRAINT discipline_pk PRIMARY KEY ( id_disciplina,
                                               cataloage_cod_catalog,
                                               cod_profil );

CREATE TABLE elevi (
    id_elev                                  INTEGER NOT NULL,
    nume_prenume_elev                        VARCHAR2(100) NOT NULL,
    telefon                                  NUMBER(10),
    email                                    VARCHAR2(150), 
--  ERROR: Column name length exceeds maximum allowed length(30) 
         activitati_de_dezvoltare_cod_activitate  INTEGER NOT NULL,
    data_nasterii                            DATE,
    burse_cod_bursa                          INTEGER NOT NULL,
    profiluri_cod_profil                     INTEGER NOT NULL,
    profile_cod_profil                       INTEGER NOT NULL
);

ALTER TABLE elevi ADD CONSTRAINT elevi_pk PRIMARY KEY ( id_elev,
                                                        profile_cod_profil );

CREATE TABLE elevi_discipline (
    orar                              DATE NOT NULL,
    elevi_id_elev                     INTEGER NOT NULL,
    discipline_id_disciplina          INTEGER NOT NULL, 
--  ERROR: Column name length exceeds maximum allowed length(30) 
         discipline_cataloage_cod_catalog  INTEGER NOT NULL,
    elevi_profiluri_cod_profil        INTEGER NOT NULL,
    cod_profil                        INTEGER NOT NULL,
    cod_profil1                       INTEGER NOT NULL
);

ALTER TABLE elevi_discipline
    ADD CONSTRAINT elevi_discipline_pk PRIMARY KEY ( elevi_id_elev,
                                                     cod_profil,
                                                     discipline_id_disciplina,
                                                     discipline_cataloage_cod_catalog,
                                                     cod_profil1 );

CREATE TABLE info_clase (
    an_scolar             VARCHAR2(10) NOT NULL,
    profiluri_cod_profil  INTEGER NOT NULL,
    profile_cod_profil    INTEGER NOT NULL
);

ALTER TABLE info_clase ADD CONSTRAINT info_clase_pk PRIMARY KEY ( profile_cod_profil );

CREATE TABLE olimpiade (
    nume_olimpiada                             VARCHAR2(200) NOT NULL,
    faza_olimpiada                             VARCHAR2(50) NOT NULL,
    locatie_desfasurare                        VARCHAR2(100) NOT NULL, 
--  ERROR: Column name length exceeds maximum allowed length(30) 
         concursuri_olimpiade_id_concurs_olimpiada  INTEGER NOT NULL, 
--  ERROR: Column name length exceeds maximum allowed length(30) 
         concursuri_olimpiade_elevi_id_elev         INTEGER
    NOT NULL, 
--  ERROR: Column name length exceeds maximum allowed length(30) 
         concursuri_olimpiade_cod_profil            INTEGER NOT NULL
);

ALTER TABLE olimpiade
    ADD CONSTRAINT olimpiade_pk PRIMARY KEY ( concursuri_olimpiade_id_concurs_olimpiada,
                                              concursuri_olimpiade_elevi_id_elev,
                                              concursuri_olimpiade_cod_profil );

CREATE TABLE profesori (
    nume_prenume_profesor  VARCHAR2(100) NOT NULL,
    telefon_profesor       NUMBER(10) NOT NULL,
    email_profesor         VARCHAR2(150),
    id_disciplina          INTEGER NOT NULL,
    cod_catalog            INTEGER NOT NULL,
    cod_profil             INTEGER NOT NULL
);

ALTER TABLE profesori
    ADD CONSTRAINT profesori_pk PRIMARY KEY ( id_disciplina,
                                              cod_catalog,
                                              cod_profil );

CREATE TABLE profile (
    cod_profil       INTEGER NOT NULL,
    denumire_profil  VARCHAR2(50) NOT NULL
);

ALTER TABLE profile ADD CONSTRAINT profile_pk PRIMARY KEY ( cod_profil );

ALTER TABLE cataloage
    ADD CONSTRAINT cataloage_clase_fk FOREIGN KEY ( clase_cod_profil )
        REFERENCES clase ( cod_profil );

ALTER TABLE clase
    ADD CONSTRAINT clase_profile_fk FOREIGN KEY ( cod_profil )
        REFERENCES profile ( cod_profil );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE concursuri
    ADD CONSTRAINT concursuri_concursuri_olimpiade_fk FOREIGN KEY ( concursuri_olimpiade_id_concurs_olimpiada,
                                                                    concursuri_olimpiade_elevi_id_elev,
                                                                    concursuri_olimpiade_cod_profil )
        REFERENCES concursuri_olimpiade ( id_concurs_olimpiada,
                                          elevi_id_elev,
                                          cod_profil );

ALTER TABLE concursuri_olimpiade
    ADD CONSTRAINT concursuri_olimpiade_elevi_fk FOREIGN KEY ( elevi_id_elev,
                                                               cod_profil )
        REFERENCES elevi ( id_elev,
                           profile_cod_profil );

ALTER TABLE discipline
    ADD CONSTRAINT discipline_cataloage_fk FOREIGN KEY ( cataloage_cod_catalog,
                                                         cod_profil )
        REFERENCES cataloage ( cod_catalog,
                               clase_cod_profil );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE elevi
    ADD CONSTRAINT elevi_activitati_de_dezvoltare_fk FOREIGN KEY ( activitati_de_dezvoltare_cod_activitate )
        REFERENCES activitati_de_dezvoltare ( cod_activitate );

ALTER TABLE elevi
    ADD CONSTRAINT elevi_burse_fk FOREIGN KEY ( burse_cod_bursa )
        REFERENCES burse ( cod_bursa );

ALTER TABLE elevi_discipline
    ADD CONSTRAINT elevi_discipline_discipline_fk FOREIGN KEY ( discipline_id_disciplina,
                                                                discipline_cataloage_cod_catalog,
                                                                cod_profil1 )
        REFERENCES discipline ( id_disciplina,
                                cataloage_cod_catalog,
                                cod_profil );

ALTER TABLE elevi_discipline
    ADD CONSTRAINT elevi_discipline_elevi_fk FOREIGN KEY ( elevi_id_elev,
                                                           cod_profil )
        REFERENCES elevi ( id_elev,
                           profile_cod_profil );

ALTER TABLE elevi
    ADD CONSTRAINT elevi_profile_fk FOREIGN KEY ( profile_cod_profil )
        REFERENCES profile ( cod_profil );

ALTER TABLE info_clase
    ADD CONSTRAINT info_clase_profile_fk FOREIGN KEY ( profile_cod_profil )
        REFERENCES profile ( cod_profil );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE olimpiade
    ADD CONSTRAINT olimpiade_concursuri_olimpiade_fk FOREIGN KEY ( concursuri_olimpiade_id_concurs_olimpiada,
                                                                   concursuri_olimpiade_elevi_id_elev,
                                                                   concursuri_olimpiade_cod_profil )
        REFERENCES concursuri_olimpiade ( id_concurs_olimpiada,
                                          elevi_id_elev,
                                          cod_profil );

ALTER TABLE profesori
    ADD CONSTRAINT profesori_discipline_fk FOREIGN KEY ( id_disciplina,
                                                         cod_catalog,
                                                         cod_profil )
        REFERENCES discipline ( id_disciplina,
                                cataloage_cod_catalog,
                                cod_profil );

--  ERROR: No Discriminator Column found in Arc Arc_2 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc Arc_2 - constraint trigger for Arc cannot be generated



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             2
-- ALTER TABLE                             26
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                  13
-- WARNINGS                                 0


-- populare tabela elevi 
INSERT INTO Elevi VALUES ('1', 'Ionescu_Bogdan',' 0758892581','ionescu.bogdan@gmail.com', TO_DATE('17/02/1995', 'dd/mm/yyyy'));
INSERT INTO Elevi VALUES ('2', 'Popescu_Tudor',' 0741290535','popescu.tudor@gmail.com', TO_DATE('3/04/1996', 'dd/mm/yyyy'));
INSERT INTO Elevi VALUES ('3', 'Prelipcean', 'Radu', '0740250673','prelipcean.radu@yahoo.com', TO_DATE('26/05/1995', 'dd/mm/yyyy'));
INSERT INTO Elevi VALUES ('4', 'Antonie', 'Ioana', '0745869453', 'antonie.ioana@yahoo.com', TO_DATE('3/01/1995', 'dd/mm/yyyy'));
INSERT INTO Elevi VALUES ('5', 'Arhire', 'Raluca','0740250123','arhire.raluca@yahoo.com', TO_DATE('26/12/1995', 'dd/mm/yyyy'));
INSERT INTO Elevi VALUES ('6', 'Panaite', 'Alexandru','0745869123','panainte.alexandru@yahoo.com', TO_DATE('13/04/1995', 'dd/mm/yyyy'));

-- populare tabela profesori
INSERT INTO Profesori VALUES ('Bodnar_Ioana','0742589632', 'bondar.ioana@yahoo.com');
INSERT INTO Profesori VALUES ('Archip_Andrada','0742545732', 'archip.andrada@yahoo.com');
INSERT INTO Profesori VALUES ('Ciobotariu_Ciprian','0742258632', 'ciobotariu.ciprian@yahoo.com');
INSERT INTO Profesori VALUES ('Bodnar_Andrei','0742358632', 'bondar.andrei@yahoo.com');
INSERT INTO Profesori VALUES ('Pavel_Ciprian','0741598632', 'pavel.ciprian@yahoo.com');
INSERT INTO Profesori VALUES ('Butnaru_Andrei','0742488632', 'butnaru.andrei@yahoo.com');

-- populare tabela discipline
INSERT INTO Discipline VALUES ('1', 'Matematica');
INSERT INTO Discipline VALUES ('2', 'Informatica');
INSERT INTO Discipline VALUES ('3', 'Fizica');
INSERT INTO Discipline VALUES ('4', 'Chimie');
INSERT INTO Discipline VALUES ('5', 'Biologie');
INSERT INTO Discipline VALUES ('6', 'Logica');
INSERT INTO Discipline VALUES ('7', 'Limba Romana');
INSERT INTO Discipline VALUES ('8', 'Educatie fizica');
INSERT INTO Discipline VALUES ('9', 'Istorie');

-- populare tabela elevi_discipline
INSERT INTO Elevi_Discipline VALUES (TO_DATE('26/10/2020', 'dd/mm/yyyy'));
INSERT INTO Elevi_Discipline VALUES (TO_DATE('27/10/2020', 'dd/mm/yyyy'));
INSERT INTO Elevi_Discipline VALUES (TO_DATE('28/10/2020', 'dd/mm/yyyy'));
INSERT INTO Elevi_Discipline VALUES (TO_DATE('29/10/2020', 'dd/mm/yyyy'));
INSERT INTO Elevi_Discipline VALUES (TO_DATE('30/10/2020', 'dd/mm/yyyy'));
INSERT INTO Elevi_Discipline VALUES (TO_DATE('31/10/2020', 'dd/mm/yyyy'));

-- populare tabela cataloage
INSERT INTO Cataloage VALUES ('1', '8', NULL, 'promovat');
INSERT INTO Cataloage VALUES ('2', '4', NULL, 'corigent');
INSERT INTO Cataloage VALUES ('3', '4', NULL, 'repetent');
INSERT INTO Cataloage  VALUES ('4', '4', NULL, 'corigent');
INSERT INTO Cataloage VALUES ('5', '9', NULL, 'promovat');
INSERT INTO Cataloage VALUES ('6', '10', NULL, 'promovat');

-- populare tabela clase
INSERT INTO Clase VALUES ('9','A', '24');
INSERT INTO Clase VALUES ('9','B', '24');
INSERT INTO Clase VALUES ('10','A', '26');
INSERT INTO Clase VALUES ('10','B', '28');
INSERT INTO Clase VALUES ('11','A', '27');
INSERT INTO Clase VALUES ('11','B', '23');
INSERT INTO Clase VALUES ('12','A', '24');
INSERT INTO Clase VALUES ('12','B', '26');

-- populare tabela profil
INSERT INTO Profil VALUES ('101', 'Matemetica-Informatica');
INSERT INTO Profil VALUES ('102', 'Stiinte ale Naturii');
INSERT INTO Profil VALUES ('103', 'Stiinte Sociale');
INSERT INTO Profil VALUES ('104', 'Filologie');
INSERT INTO Profil VALUES ('105', 'Matemetica-Informatica');
INSERT INTO Profil VALUES ('106', 'Matemetica-Informatica');

-- populare tabela info_clase
INSERT INTO Info_clase VALUES ('2015-2016');
INSERT INTO Info_clase VALUES ('2016-2017');
INSERT INTO Info_clase VALUES ('2017-2018');
INSERT INTO Info_clase VALUES ('2018-2019');
INSERT INTO Info_clase VALUES ('2019-2020');

-- populare tabela burse
INSERT INTO Burse VALUES ('201','Bursa de merit', '500');
INSERT INTO Burse VALUES ('202','Bursa sociala', '400');
INSERT INTO Burse VALUES ('203','Bursa medicala', '800');

-- populare tabela activitati de dezvoltare
INSERT INTO Activitati_de_Dezvoltare VALUES ('110', 'Sah', '20');
INSERT INTO Activitati_de_Dezvoltare VALUES ('111', 'Pian', '12');
INSERT INTO Activitati_de_Dezvoltare VALUES ('112', 'Baschet', '11');
INSERT INTO Activitati_de_Dezvoltare VALUES ('113', 'Fotbal', '14');
INSERT INTO Activitati_de_Dezvoltare VALUES ('114', 'Volei', '15');

-- populare tabela Concurs_Olimpiada
INSERT INTO Concurs_Olimpiada VALUES ('303','Premiu I','99 puncte');
INSERT INTO Concurs_Olimpiada VALUES ('304','Premiu II','84 puncte');
INSERT INTO Concurs_Olimpiada VALUES ('305','Premiu III','76 puncte');
INSERT INTO Concurs_Olimpiada VALUES ('306','Mentiune','62 puncte');
INSERT INTO Concurs_Olimpiada VALUES ('307','Premiu I','96 puncte');
INSERT INTO Concurs_Olimpiada VALUES ('308','Premiu II','88 puncte');
INSERT INTO Concurs_Olimpiada VALUES ('309','Premiu III','67 puncte');
INSERT INTO Concurs_Olimpiada VALUES ('310','Mentiune','65 puncte');

-- populare tabela Concurs
INSERT INTO Concursuri VALUES ('Concursul Electra', 'Matematica', '(TO_DATE('12/03/2019', 'dd/mm/yyyy'))');
INSERT INTO Concursuri VALUES ('Concursul Olimpia', 'Limba romana', '(TO_DATE('16/04/2019', 'dd/mm/yyyy'))');
INSERT INTO Concursuri VALUES ('Concursul de Biologie', 'Biologie', '(TO_DATE('18/06/2019', 'dd/mm/yyyy'))');
INSERT INTO Concursuri VALUES ('Concursul Istoria Chinei', 'Istorie', '(TO_DATE('05/07/2019', 'dd/mm/yyyy'))');
INSERT INTO Concursuri VALUES ('Concursul de Informatica', 'Informatica', '(TO_DATE('20/08/2019', 'dd/mm/yyyy'))');

-- populare tabela Olimpiada
INSERT INTO Olimpiada VALUES ('12','Locala','Vaslui');
INSERT INTO Olimpiada VALUES ('13','Locala','Bacau');
INSERT INTO Olimpiada VALUES ('14','Judeteana','Iasi');
INSERT INTO Olimpiada VALUES ('15','Nationala','Bucuresti');
