drop table activitati_de_dezvoltare;
drop table burse;
drop table clase;

drop table concursuri_olimpiade;
drop table discipline;
drop table orare;
drop table profesori;
drop table profile;
drop table cataloage;
drop table elevi;

-- Generated by Oracle SQL Developer Data Modeler 20.3.0.283.0710
--   at:        2021-01-09 18:25:05 EET
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE activitati_de_dezvoltare (
    cod_activitate         INTEGER NOT NULL,
    denumire_activitate    VARCHAR2(150),
    capacitate_activitate  NUMBER(2)
);

ALTER TABLE activitati_de_dezvoltare ADD CONSTRAINT activitati_de_dezvoltare_pk PRIMARY KEY ( cod_activitate );

CREATE TABLE burse (
    cod_bursa       INTEGER NOT NULL,
    denumire_bursa  VARCHAR2(150),
    valoare_bursa   INTEGER
);

ALTER TABLE burse ADD CONSTRAINT burse_pk PRIMARY KEY ( cod_bursa );

CREATE TABLE cataloage (
    cod_catalog        INTEGER NOT NULL,
    medie_note         INTEGER,
    absenta            DATE,
    denumire_situatie  VARCHAR2(20)
);

ALTER TABLE cataloage ADD CONSTRAINT cataloage_pk PRIMARY KEY ( cod_catalog );

CREATE TABLE clase (
    an_clasa               VARCHAR2(4) NOT NULL,
    grupa_clasa            VARCHAR2(1) NOT NULL,
    capacitate_clasa       NUMBER(2) NOT NULL,
    profile_cod_profil     INTEGER NOT NULL,
    cataloage_cod_catalog  INTEGER NOT NULL,
    an_scolar              CHAR(10),
    orare_data_disciplina  DATE NOT NULL
);

CREATE UNIQUE INDEX clase__idx ON
    clase (
        cataloage_cod_catalog
    ASC );

CREATE UNIQUE INDEX clase__idxv1 ON
    clase (
        orare_data_disciplina
    ASC );

ALTER TABLE clase
    ADD CONSTRAINT clase_pk PRIMARY KEY ( an_clasa,
                                          grupa_clasa,
                                          profile_cod_profil );

CREATE TABLE concursuri (
    nume_concurs                               VARCHAR2(100),
    materie_testata                            VARCHAR2(50),
    perioada                                   DATE, 
--  ERROR: Column name length exceeds maximum allowed length(30) 
         concursuri_olimpiade_id_concurs_olimpiada  INTEGER NOT NULL
);

CREATE TABLE concursuri_olimpiade (
    id_concurs_olimpiada  INTEGER NOT NULL,
    tip_premiu_obtinut    VARCHAR2(100),
    punctaj_acumulat      NUMBER(4),
    elevi_id_elev         INTEGER NOT NULL,
    elevi_cod_activitate  INTEGER NOT NULL,
    elevi_cod_bursa       INTEGER NOT NULL,
    elevi_an_clasa        VARCHAR2(4) NOT NULL,
    elevi_grupa_clasa     VARCHAR2(1) NOT NULL,
    elevi_cod_profil      INTEGER NOT NULL
);

ALTER TABLE concursuri_olimpiade ADD CONSTRAINT concursuri_olimpiade_pk PRIMARY KEY ( id_concurs_olimpiada );

CREATE TABLE discipline (
    id_discplina           INTEGER NOT NULL,
    denumire_desciplina    VARCHAR2(150) NOT NULL,
    profesori_id_profesor  INTEGER NOT NULL,
    cataloage_cod_catalog  INTEGER NOT NULL
);

ALTER TABLE discipline ADD CONSTRAINT discipline_pk PRIMARY KEY ( id_discplina,
                                                                  profesori_id_profesor );

CREATE TABLE elevi (
    id_elev                                  INTEGER NOT NULL,
    nume_prenume_elev                        VARCHAR2(100) NOT NULL,
    telefon                                  NUMBER(10),
    email                                    VARCHAR2(150),
    data_nasterii                            DATE, 
--  ERROR: Column name length exceeds maximum allowed length(30) 
         activitati_de_dezvoltare_cod_activitate  INTEGER NOT NULL,
    burse_cod_bursa                          INTEGER NOT NULL,
    clase_an_clasa                           VARCHAR2(4) NOT NULL,
    clase_grupa_clasa                        VARCHAR2(1) NOT NULL,
    clase_cod_profil                         INTEGER NOT NULL
);

ALTER TABLE elevi
    ADD CONSTRAINT elevi_pk PRIMARY KEY ( id_elev,
                                          activitati_de_dezvoltare_cod_activitate,
                                          burse_cod_bursa,
                                          clase_an_clasa,
                                          clase_grupa_clasa,
                                          clase_cod_profil );

CREATE TABLE olimpiade (
    nume_olimpiada                             VARCHAR2(150),
    faza_olimpiada                             VARCHAR2(150),
    locatie_olimpiada                          VARCHAR2(100), 
--  ERROR: Column name length exceeds maximum allowed length(30) 
         concursuri_olimpiade_id_concurs_olimpiada  INTEGER NOT NULL
);

CREATE TABLE orare (
    data_disciplina DATE NOT NULL
);

ALTER TABLE orare ADD CONSTRAINT orare_pk PRIMARY KEY ( data_disciplina );

CREATE TABLE profesori (
    id_profesor            INTEGER NOT NULL,
    nume_prenume_profesor  VARCHAR2(100) NOT NULL,
    telefon_profesor       NUMBER(10),
    email_profesor         VARCHAR2(150)
);

ALTER TABLE profesori ADD CONSTRAINT profesori_pk PRIMARY KEY ( id_profesor );

CREATE TABLE profile (
    cod_profil       INTEGER NOT NULL,
    denumire_profil  VARCHAR2(50) NOT NULL
);

ALTER TABLE profile ADD CONSTRAINT profile_pk PRIMARY KEY ( cod_profil );

ALTER TABLE clase
    ADD CONSTRAINT clase_cataloage_fk FOREIGN KEY ( cataloage_cod_catalog )
        REFERENCES cataloage ( cod_catalog );

ALTER TABLE clase
    ADD CONSTRAINT clase_orare_fk FOREIGN KEY ( orare_data_disciplina )
        REFERENCES orare ( data_disciplina );

ALTER TABLE clase
    ADD CONSTRAINT clase_profile_fk FOREIGN KEY ( profile_cod_profil )
        REFERENCES profile ( cod_profil );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE concursuri
    ADD CONSTRAINT concursuri_concursuri_olimpiade_fk FOREIGN KEY ( concursuri_olimpiade_id_concurs_olimpiada )
        REFERENCES concursuri_olimpiade ( id_concurs_olimpiada );

ALTER TABLE concursuri_olimpiade
    ADD CONSTRAINT concursuri_olimpiade_elevi_fk FOREIGN KEY ( elevi_id_elev,
                                                               elevi_cod_activitate,
                                                               elevi_cod_bursa,
                                                               elevi_an_clasa,
                                                               elevi_grupa_clasa,
                                                               elevi_cod_profil )
        REFERENCES elevi ( id_elev,
                           activitati_de_dezvoltare_cod_activitate,
                           burse_cod_bursa,
                           clase_an_clasa,
                           clase_grupa_clasa,
                           clase_cod_profil );

ALTER TABLE discipline
    ADD CONSTRAINT discipline_cataloage_fk FOREIGN KEY ( cataloage_cod_catalog )
        REFERENCES cataloage ( cod_catalog );

ALTER TABLE discipline
    ADD CONSTRAINT discipline_profesori_fk FOREIGN KEY ( profesori_id_profesor )
        REFERENCES profesori ( id_profesor );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE elevi
    ADD CONSTRAINT elevi_activitati_de_dezvoltare_fk FOREIGN KEY ( activitati_de_dezvoltare_cod_activitate )
        REFERENCES activitati_de_dezvoltare ( cod_activitate );

ALTER TABLE elevi
    ADD CONSTRAINT elevi_burse_fk FOREIGN KEY ( burse_cod_bursa )
        REFERENCES burse ( cod_bursa );

ALTER TABLE elevi
    ADD CONSTRAINT elevi_clase_fk FOREIGN KEY ( clase_an_clasa,
                                                clase_grupa_clasa,
                                                clase_cod_profil )
        REFERENCES clase ( an_clasa,
                           grupa_clasa,
                           profile_cod_profil );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE olimpiade
    ADD CONSTRAINT olimpiade_concursuri_olimpiade_fk FOREIGN KEY ( concursuri_olimpiade_id_concurs_olimpiada )
        REFERENCES concursuri_olimpiade ( id_concurs_olimpiada );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             2
-- ALTER TABLE                             21
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   6
-- WARNINGS                                 0
